# to be ran after dist_ortho on the file generated by protdist - arranges the output to a format usable by absense

# phylip stuff
focal_sp = "DSUZ"
protdist_outfile_fp = "./out/outfile"
outfile_fp = "./out/distances.txt"

species = []
focal_dists = []

with open(protdist_outfile_fp) as f:
  count = None

  sp = None
  curr = 0

  while True:
    line = f.readline().strip()

    # eof
    if line == "" or line == None:
      break

    # header
    if count == None:
      count = int(line)
      continue

    if sp == None:
      sp = line[:10].strip()
      line = line[10:].strip()

      species.append(sp)

    dists = line.split("  ")
    curr += len(dists)

    # focal sp dists
    if sp == focal_sp:
      focal_dists += dists

    if curr == count:
      sp = None
      curr = 0

distances = dict(zip(species, focal_dists))

outfile = open(outfile_fp, "w+")

for sp, dist in distances.items():
  outfile.write("{}\t{}\n".format(sp, dist))
